### ISSUE TITLE
Question: Do I need an iText license to use this?

### ISSUE THREAD

**Issue by pedroadame** [vkononov/fillable-pdf#1]
As said. Please answer, generating fillable PDFs in Ruby is really necessary in our current big project.

**Comment by vkononov** [comment]
Hello there,

The iText jar used by the plugin is free to use. As is the rjb gem, upon which this gem relies.

You can find the iText license inside the iText.zip file on https://github.com/itext/itextpdf/releases/tag/5.5.11, but here is a copy:

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License version 3
    as published by the Free Software Foundation with the addition of the
    following permission added to Section 15 as permitted in Section 7(a):
    FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY
    ITEXT GROUP. ITEXT GROUP DISCLAIMS THE WARRANTY OF NON INFRINGEMENT
    OF THIRD PARTY RIGHTS
    
    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.
    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, see http://www.gnu.org/licenses or write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA, 02110-1301 USA, or download the license from the following URL:
    http://itextpdf.com/terms-of-use/
    
    The interactive user interfaces in modified source and object code versions
    of this program must display Appropriate Legal Notices, as required under
    Section 5 of the GNU Affero General Public License.
    
    In accordance with Section 7(b) of the GNU Affero General Public License,
    a covered work must retain the producer line in every PDF that is created
    or manipulated using iText.
    
    You can be released from the requirements of the license by purchasing
    a commercial license. Buying such a license is mandatory as soon as you
    develop commercial activities involving the iText software without
    disclosing the source code of your own applications.
    These activities include: offering paid services to customers as an ASP,
    serving PDFs on the fly in a web application, shipping iText with a closed
    source product.
    
    For more information, please contact iText Software Corp. at this
    address: sales@itextpdf.com

Thanks for using my gem. :)

Vadim

On July 31, 2017 at 2:25:16 AM, Pedro Adame Vergara (notifications@github.com) wrote:

As said. Please answer, generating fillable PDFs in Ruby is really necessary in our current big project.

**Comment by pedroadame** [comment]
Thank you :)

**Comment by gamesover** [comment]
Is iText still free to use now? https://github.com/itext/itext7/blob/develop/LICENSE.md

https://itextpdf.com/en/resources/faq/sales/itext-7/itext-free

```
We have a dual licensing business model. You can use the SDK at no cost if you open source the application you are integrating the iText SDK into per the terms of the AGPL license, or you can license iText commercially if you don’t want to open source your entire application.

Click here to request your free quote.
```

To me, it is quite straightforward. It is only free for open source project.

**Comment by vkononov** [comment]
Thanks for pointing it out @gamesover. It seems that iText 7 is licensed differently than iText 5.

I'm not a lawyer, so I cannot speak to what iText licenses mean, but I will add a note both in the `README.md` and in the `LICENSE.txt` files that an iText license may be required.
