### ISSUE TITLE
Not all fields from the editable PDF are visible

### ISSUE THREAD

**Issue by arth-complitech** [vkononov/fillable-pdf#10]
I have a PDF form of some third-party service registration, they have around 180 fields in the form.
Unfortunately, not all the fields are coming up when I call pdf.fields method.

**Comment by vkononov** [comment]
Would you be willing to share that form so that I can test?

**Comment by arth-complitech** [comment]
I'm sorry they are visible. They weren't in sequence and I failed to check all the results of pdf.fields method as there were around 180 fields in that form.
