### ISSUE TITLE
How to use fillable pdf gem in Rubymine on Windows

### ISSUE THREAD

**Issue by zhanaz1NW** [vkononov/fillable-pdf#12]
I've installed fillable-pdf in my rubymine. The methods, coming from FillablePdf class are accessible. However, when I am trying to run my feature file, it gives me the following error `import': NoClassDefFoundError. My Java_Home is set. and I am using Windows 10, ruby version is 2.4.0 . Could you pls help me on this

**Comment by vkononov** [comment]
Sorry to reply so late, but if you see a `NoClassDefFoundError` error, this is not a problem with the gem but with your Java setup. I can almost guarantee that if you try to run other Java programs, you will get an identical error. Unfortunately, I've never tried running this on a Windows. I've only tested on Mac and Linux.
