### ISSUE TITLE
"Invalid cross-device link @ rb_file_s_rename" errors, when calling .save inside of a docker container (workaround included)

### ISSUE THREAD

**Issue by xxx** [vkononov/fillable-pdf#15]
Hi, thank you for creating this gem.

I've run into an issue building a service due to FillablePDF using `File.rename` in its `save` method - this throws errors when run inside of a Docker container.

I've worked around this for now with a monkeypatch to `save`, that uses `FileUtils.mv` rather than `File.rename`. I can put up a PR for this if you'd like.

**Comment by vkononov** [comment]
Hi, @xxx. Thanks for letting me know this. If you could do a PR, that would be awesome. Thank you!

**Comment by xxx** [comment]
going to close this out now that #16 is up

**Comment by vkononov** [comment]
Merged! Thanks, @xxx.
