### ISSUE TITLE
Checkboxes not able to uncheck

### ISSUE THREAD

**Issue by benjing** [vkononov/fillable-pdf#17]
When filling a form with simple checkboxes in it, cannot uncheck the boxes and passing any value even nil makes the checkboxes appear checked. Looking at the pdf in adobe the values used are appearing as export values.
values tried:
true
false
"No"
"Yes"
"NO"
"YES"
""
nil
"true"
"false"
"True"
"False"
1
0
"1"
"0"

**Comment by simonfranzen** [comment]
We are facing the same problem. Check works, uncheck not.

**Comment by simonfranzen** [comment]
Found out, that  `def set_field(key, value)` is using a `to_s` when setting the value

I was able to uncheck the Buttons with `pdf.pdf_field(key).setValue(nil)`

**Comment by vkononov** [comment]
@benjing @simonfranzen Thanks for reporting this. The correct way to unset a checkbox is with the `'Off'` value (String with title case). I will update the README.md to include this use case.
