### ISSUE TITLE
Setting Checkbox Values and Formatting

### ISSUE THREAD

**Issue by johneastman** [vkononov/fillable-pdf#25]
### Setting Checkbox Values
When using `set_values`, it seems like if any value is set to the checkbox's key, including `nil`, the checkbox will be checked. The only way to uncheck the box was to remove it's associate key from the hash of values passed to that method.

### Checkbox Display
After a checkbox value has been set to `'Yes'` or `'Off'`, the actual formatting is different from what I would expect. For example, `'Off'`/unchecked check boxes seem to be set to an empty square, and `'Yes'`/checked boxes display both an empty box and an offset `X`.

### Expected
<img width="215" alt="Screen Shot 2022-09-14 at 10 34 09 AM" src="https://user-images.githubusercontent.com/40542809/190212525-995ba514-9b09-427f-b8f5-202a9ec1f888.png">

(I also see this in my PDF, though the above image is closer to what I'd expect)
<img width="215" alt="Screen Shot 2022-09-14 at 10 31 05 AM" src="https://user-images.githubusercontent.com/40542809/190212626-0e2b7903-cb40-4f93-acb3-0a6fa77b5492.png">

### Actual
<img width="201" alt="Screen Shot 2022-09-14 at 10 30 07 AM" src="https://user-images.githubusercontent.com/40542809/190212676-274277ba-b069-4e38-abed-ee050a22b419.png">

**Comment by vkononov** [comment]
Thanks for reporting this issue, @johneastman. I've fixed this problem in [v0.9.5](https://github.com/vkononov/fillable-pdf/releases/tag/v0.9.5).

**Comment by vkononov** [comment]
These custom appearances are now controlled by the `generate_appearance` flag. See `README.md` for more details.
