### ISSUE TITLE
 warning: undefining the allocator of T_DATA class Rjb::Java_lang_Class

### ISSUE THREAD

**Issue by tfader** [vkononov/fillable-pdf#36]
from long time:
itext.rb:4: warning: undefining the allocator of T_DATA class Rjb::Java_lang_Class

**Comment by vkononov** [comment]
@tfader What do you mean "from long time"?

And what exactly is this issue about? Posting a vague Java warning on a Ruby project tells me nothing about what you're doing or what you're experiencing.

**Comment by tfader** [comment]
"from long time ago" means from around 2 months. Sorry for my mistake.
I think that was starts after latest rjb gem version was installed but rollback to previous rib version doesn't fix it.
My stack:
java 20.0.1
rails 7.0.4.2
ruby 3.2.1
rjb 1.6.7
fillable-pdf 0.9.5.2

**Comment by vkononov** [comment]
So, what is the problem you're experiencing? All you've given me as a warning without any description of the issue or any code to replicate the issue.

**Comment by tfader** [comment]
Each call application, doesn't matter what it is: rails console, rails server, nginx passenger, sidekiq etc output warning as I mentioned at the beginning. It is not a big deal but on each file the warning message are included.

**Comment by vkononov** [comment]
I've taken a look at this warning, and it's coming from the [rjb](https://github.com/arton/rjb) gem. Please submit your issue there instead. Alternatively, you can wrap your calls to `fillable-pdf` in a block that suppresses warning, similar to how it is done [here](https://github.com/vkononov/fillable-pdf/blob/master/lib/fillable-pdf/kernel.rb).
