### ISSUE TITLE
Rails 6 compatibility

### ISSUE THREAD

**Issue by adamnaamani** [vkononov/fillable-pdf#5]
After upgrading Rails to version 6.0.0, I received this error after running a task:

```
/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: already initialized constant Rjb::Com_itextpdf_kernel_pdf_PdfName::A
/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: previous definition of A was here
/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: already initialized constant Rjb::Com_itextpdf_kernel_pdf_PdfName::R
/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: previous definition of R was here
```

**Comment by adamnaamani** [comment]
> Thanks for reporting this, @adamnaamani. Wanted to get a little more detail from you. Based on what you sent me, these are just warnings. Are they actually causing your application not to work?

No problem. Confirmed it's just a warning, but haven't tested the actual gem yet, will let you know if I run into any issues.

**Comment by vkononov** [comment]
Sounds good! I've tested this warning, and it looks like it's an issue with the rjb gem that my gem uses. I will open a ticket with the rjb developer.
