### ISSUE TITLE
Gem Load Error: Constants DL and Fiddle is not defined.

### ISSUE THREAD

**Issue by sirramongabriel** [vkononov/fillable-pdf#6]
Hello, I'm having trouble loading your library.

### Expected Behavior
when typing rails server in the terminal, for the dev-server to start without error.

### Current Behavior

- error msg: There was an error while trying to load the gem 'fillable-pdf'. (Bundler::GemRequireError)
- Gem Load Error is: Constants DL and Fiddle is not defined.
- Typing require 'fiddle' in irb succeeds

### Possible Solution
adding require: false to 'fillable-pdf' in Gemfile only pushes the error further down as RuntimeError

### Steps to Reproduce

- bundle with  'rjb', '~> 1.6.1' &  'fillable-pdf' in gemfile
- try to start the server

 
### Context (Environment)

- Ubuntu 18.04 LTS 
- Ruby 2.3.8
- Rails 5.2.3
- Puma 3.11

### Detailed Description

`There was an error while trying to load the gem 'fillable-pdf'. (Bundler::GemRequireError)
Gem Load Error is: Constants DL and Fiddle is not defined.
Backtrace for gem load error is:
/home/barracus/.rvm/gems/ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/fillable-pdf/itext.rb:3:in `load'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/fillable-pdf/itext.rb:3:in `<main>'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/fillable-pdf.rb:1:in `<main>'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
/home/barracus/Documents/codes/ruby/rails/522/whizcharts/config/application.rb:20:in `<main>'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:6:in `<main>'
Bundler Error Backtrace:
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
	from /home/barracus/Documents/codes/ruby/rails/522/whizcharts/config/application.rb:20:in `<main>'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/barracus/.rvm/gems/ruby-2.3.8/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:6:in `<main>'
`

**Comment by sirramongabriel** [comment]
The temporary solution from [arton/rjb issue: #70 ](https://github.com/arton/rjb/issues/70) worked for me &  shares the following output when starting Puma:

`ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: already initialized constant Rjb::Com_itextpdf_kernel_pdf_PdfName::A
ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: previous definition of A was here
ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: already initialized constant Rjb::Com_itextpdf_kernel_pdf_PdfName::R
ruby-2.3.8/gems/fillable-pdf-0.7.1/lib/field.rb:4: warning: previous definition of R was here`

###Solution
`ln -s /usr/lib/jvm/java-11-openjdk-amd64/lib/server /usr/lib/jvm/java-11-openjdk-amd64/jre/lib/amd64/server
`
In case someone else runs into this and doesn't know what 'ln -s' does.
[What is a symlink?](https://www.computerhope.com/unix/uln.htm)

Finally, apologies as this is an 'rjb' issue already answered. It wasn't apparent in the error message I received at the time of writing.

**Comment by vkononov** [comment]
I suspected this was an `rjb` issue, but haven't had the time to investigate. Thank you for looking into this for me, @sirramongabriel.
