### ISSUE TITLE
No spec around the Field::SIGNATURE feature

### ISSUE THREAD

**Issue by uchilaka** [vkononov/fillable-pdf#9]
My team is considering using this library, but there are no specs included for what it looks like to include a signature in a document. What use case is supported here:

* A signature in image format, like perhaps a `base64` string? (this would be best aligned with my project's use case)
* A digital signature? (which is what I suspect after looking at the iText SDK - but which wouldn't address my team's use case)
* Some other format for the signature? 

Would greatly appreciate feedback from the team! Glad to also contribute updates to the spec if you can point me in the right direction for what this looks like, perhaps with a gist showing it in use, or link to a sample project?

**Comment by MatUrbanski** [comment]
+1

**Comment by vkononov** [comment]
This feature to add both base64 encoded images and images from files has been added in [v0.9.3](https://github.com/vkononov/fillable-pdf/releases/tag/v0.9.3).
